//Aries
{$.ajax({
    type:'POST',
    url:'https://aztro.sameerkumar.website?sign=aries&day=today',
    success:function(data){
    $('#ariesDaily').append(data.description)
    }
     });
}

//Taurus
{$.ajax({
    type:'POST',
    url:'https://aztro.sameerkumar.website?sign=taurus&day=today',
    success:function(data){
    $('#taurusDaily').append(data.description)
    }
     });
}

//Gemini
{$.ajax({
    type:'POST',
    url:'https://aztro.sameerkumar.website?sign=gemini&day=today',
    success:function(data){
    $('#geminiDaily').append(data.description)
    }
     });
}

//Cancer
{$.ajax({
    type:'POST',
    url:'https://aztro.sameerkumar.website?sign=cancer&day=today',
    success:function(data){
    $('#cancerDaily').append(data.description)
    }
     });
}

//Leo
{$.ajax({
    type:'POST',
    url:'https://aztro.sameerkumar.website?sign=leo&day=today',
    success:function(data){
    $('#leoDaily').append(data.description)
    }
     });
}

//Virgo
{$.ajax({
    type:'POST',
    url:'https://aztro.sameerkumar.website?sign=virgo&day=today',
    success:function(data){
    $('#virgoDaily').append(data.description)
    }
     });
}

//Libra
{$.ajax({
    type:'POST',
    url:'https://aztro.sameerkumar.website?sign=libra&day=today',
    success:function(data){
    $('#libraDaily').append(data.description)
    }
     });
}

//Scorpio
{$.ajax({
    type:'POST',
    url:'https://aztro.sameerkumar.website?sign=scorpio&day=today',
    success:function(data){
    $('#scorpioDaily').append(data.description)
    }
     });
}

//Sagittarius
{$.ajax({
    type:'POST',
    url:'https://aztro.sameerkumar.website?sign=sagittarius&day=today',
    success:function(data){
    $('#sagittariusDaily').append(data.description)
    }
     });
}

//Capricorn
{$.ajax({
    type:'POST',
    url:'https://aztro.sameerkumar.website?sign=capricorn&day=today',
    success:function(data){
    $('#capricornDaily').append(data.description)
    }
     });
}

//Aquarius
{$.ajax({
    type:'POST',
    url:'https://aztro.sameerkumar.website?sign=aquarius&day=today',
    success:function(data){
    $('#aquariusDaily').append(data.description)
    }
     });
}

//Pisces
{$.ajax({
    type:'POST',
    url:'https://aztro.sameerkumar.website?sign=pisces&day=today',
    success:function(data){
    $('#piscesDaily').append(data.description)
    }
     });
}